# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
import Test
import pickle
import numpy as np
import pandas as pd


f="/Users/HP/Desktop/iskander/our_model.sav"
loaded_model = pickle.load(open(f, 'rb'))
heart =pd.read_csv("/Users/HP/Desktop/Iskander/heart.csv")


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(1010, 772)
        self.label = QtWidgets.QLabel(widget)
        self.label.setGeometry(QtCore.QRect(60, 110, 121, 251))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(widget)
        self.label_2.setGeometry(QtCore.QRect(-20, -50, 1031, 831))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("background-image:url(:/newPrefix/AI-Healthcare.jpg)")
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/AI-Healthcare.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(widget)
        self.pushButton.clicked.connect(self.Clickeddd)
        self.pushButton.setGeometry(QtCore.QRect(820, 680, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code Light")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:rgb(158, 133, 255);\n"
"font: 18pt \"Cascadia Code\";\n"
"font: 75 18pt \"Cascadia Code\";\n"
"\n"
"font: 30 18pt \"Cascadia Code Light\";")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(widget)
        self.label_3.setGeometry(QtCore.QRect(10, 190, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(widget)
        self.label_4.setGeometry(QtCore.QRect(20, 50, 641, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 8pt \"Cascadia Code\";\n"
"font: 18pt \"Cascadia Code\";")
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(widget)
        self.label_5.setGeometry(QtCore.QRect(10, 260, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(widget)
        self.label_6.setGeometry(QtCore.QRect(30, 340, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(widget)
        self.label_7.setGeometry(QtCore.QRect(640, 190, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("")
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(widget)
        self.label_8.setGeometry(QtCore.QRect(30, 600, 160, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("")
        self.label_8.setScaledContents(True)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(False)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(widget)
        self.label_9.setGeometry(QtCore.QRect(30, 520, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("")
        self.label_9.setScaledContents(True)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(False)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(widget)
        self.label_10.setGeometry(QtCore.QRect(20, 440, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("")
        self.label_10.setScaledContents(True)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setWordWrap(False)
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(widget)
        self.label_12.setGeometry(QtCore.QRect(640, 540, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("")
        self.label_12.setScaledContents(True)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setWordWrap(False)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(widget)
        self.label_13.setGeometry(QtCore.QRect(640, 460, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("")
        self.label_13.setScaledContents(True)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setWordWrap(False)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(widget)
        self.label_14.setGeometry(QtCore.QRect(620, 340, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("")
        self.label_14.setScaledContents(True)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setWordWrap(False)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(widget)
        self.label_15.setGeometry(QtCore.QRect(640, 260, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("")
        self.label_15.setScaledContents(True)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setWordWrap(False)
        self.label_15.setObjectName("label_15")
        self.lineEdit = QtWidgets.QLineEdit(widget)
        self.lineEdit.setGeometry(QtCore.QRect(230, 200, 151, 22))
        self.lineEdit.setStyleSheet("background-color:rgb(254, 234, 255)")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_5 = QtWidgets.QLineEdit(widget)
        self.lineEdit_5.setGeometry(QtCore.QRect(230, 610, 151, 22))
        self.lineEdit_5.setStyleSheet("background-color:rgb(254, 234, 255)")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(widget)
        self.lineEdit_6.setGeometry(QtCore.QRect(230, 530, 151, 22))
        self.lineEdit_6.setStyleSheet("background-color:rgb(254, 234, 255)")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(widget)
        self.lineEdit_7.setGeometry(QtCore.QRect(230, 450, 151, 22))
        self.lineEdit_7.setStyleSheet("background-color:rgb(254, 234, 255)")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_9 = QtWidgets.QLineEdit(widget)
        self.lineEdit_9.setGeometry(QtCore.QRect(850, 470, 151, 22))
        self.lineEdit_9.setStyleSheet("background-color:rgb(254, 234, 255)")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(widget)
        self.lineEdit_10.setGeometry(QtCore.QRect(860, 270, 141, 22))
        self.lineEdit_10.setStyleSheet("background-color:rgb(254, 234, 255)")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.comboBox = QtWidgets.QComboBox(widget)
        self.comboBox.setGeometry(QtCore.QRect(230, 270, 151, 22))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(widget)
        self.comboBox_2.setGeometry(QtCore.QRect(860, 350, 141, 22))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(widget)
        self.comboBox_3.setGeometry(QtCore.QRect(860, 200, 141, 22))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(widget)
        self.comboBox_4.setGeometry(QtCore.QRect(850, 550, 151, 22))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(widget)
        self.comboBox_5.setGeometry(QtCore.QRect(230, 350, 151, 22))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_11 = QtWidgets.QLabel(widget)
        self.label_11.setGeometry(QtCore.QRect(110, 700, 651, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("font: 75 16pt \"Cascadia Code\";\n"
"font: 14pt \"Cascadia Code\";")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "app"))
        self.pushButton.setText(_translate("widget", "Predict"))
        self.label_3.setText(_translate("widget", "Age:"))
        self.label_4.setText(_translate("widget", "Please Fill the fields below:"))
        self.label_5.setText(_translate("widget", "Sex:"))
        self.label_6.setText(_translate("widget", "ChestPainType:"))
        self.label_7.setText(_translate("widget", "RestingECG:"))
        self.label_8.setText(_translate("widget", "FastingBGp:"))
        self.label_9.setText(_translate("widget", "Cholesterol:"))
        self.label_10.setText(_translate("widget", "RestingBp:"))
        self.label_12.setText(_translate("widget", "StSlope:"))
        self.label_13.setText(_translate("widget", "OldPeak:"))
        self.label_14.setText(_translate("widget", "ExerciseAngina:"))
        self.label_15.setText(_translate("widget", "MaxHR:"))
        self.comboBox.setItemText(0, _translate("widget", "Male"))
        self.comboBox.setItemText(1, _translate("widget", "Female"))
        self.comboBox_2.setItemText(0, _translate("widget", "N"))
        self.comboBox_2.setItemText(1, _translate("widget", "Y"))
        self.comboBox_3.setItemText(0, _translate("widget", "Normal"))
        self.comboBox_3.setItemText(1, _translate("widget", "LVH"))
        self.comboBox_3.setItemText(2, _translate("widget", "ST"))
        self.comboBox_4.setItemText(0, _translate("widget", "Up"))
        self.comboBox_4.setItemText(1, _translate("widget", "Flat"))
        self.comboBox_4.setItemText(2, _translate("widget", "Down"))
        self.comboBox_5.setItemText(0, _translate("widget", "ATA"))
        self.comboBox_5.setItemText(1, _translate("widget", "NAP"))
        self.comboBox_5.setItemText(2, _translate("widget", "ASY"))
        self.comboBox_5.setItemText(3, _translate("widget", "TA"))
    def Clickeddd(self):
        self.gettingthefield()

    def gettingthefield(self):
        
        age=self.lineEdit.text()
        fastingbgp=self.lineEdit_5.text()
        cholesterol=self.lineEdit_6.text()
        Restingbp=self.lineEdit_7.text()
        oldpeak=self.lineEdit_9.text()
        maxhr=self.lineEdit_10.text()
        sex=self.comboBox.currentText()
        exerciseangina=self.comboBox_2.currentText()
        restingecg=self.comboBox_3.currentText()
        stslope=self.comboBox_4.currentText()
        chestpaintype=self.comboBox_5.currentText()

        if chestpaintype=='NAP':
            chestpaintype=0
        if chestpaintype=='TA':
            chestpaintype=1 
        if chestpaintype=='ATA':
            chestpaintype=2       
        if chestpaintype=='ASY':
            chestpaintype=3
        if restingecg=='Normal':
            restingecg=0
        if restingecg=='ST':
            restingecg=1
        if restingecg=='LVH':
            restingecg=2            
        if stslope=='Down':
            stslope=2
        if stslope=='Flat':
            stslope=0
        if stslope=='Up':
            stslope=1   
        if sex=='Male':
            sex=1 
        else: 
            sex=0
        if exerciseangina=='N':
            exerciseangina=0
        else:
            exerciseangina=1    
        to_predict=heart.iloc[1,:-1] 
        to_predict.Age=age
        to_predict.Sex=sex
        to_predict.ChestPainType=chestpaintype
        to_predict.RestingBP=Restingbp
        to_predict.Cholesterol=cholesterol
        to_predict.FastingBS=fastingbgp
        to_predict.RestingECG=restingecg
        to_predict.MaxHR=maxhr
        to_predict.ExerciseAngina=exerciseangina
        to_predict.Oldpeak=oldpeak
        to_predict.ST_Slope=stslope


        to_p=np.array(to_predict).reshape(1,11)
        result=loaded_model.predict(to_p)          
        if result[0]==0:

            
            self.label_11.setText('no risks,you good to carry on with your life')
            
        else:
            self.label_11.setText('guess you having some serious problems mate')  
            


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QWidget()
    ui = Ui_widget()
    ui.setupUi(widget)
    widget.show()
    sys.exit(app.exec_())
